# Generated by Django 3.1.2 on 2020-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201028_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(help_text='Введите статус', max_length=50, unique=True, verbose_name='Статус'),
        ),
    ]
